local M = {}

-- GitHub-style aliases taken from rxaviers emoji cheatsheet:
-- https://gist.github.com/rxaviers/7360908#file-gistfile1-md
local emoji_map = {
	["BOWTIE"] = ":bowtie:",
	["SMILE"] = "😄",
	["LAUGHING"] = "😆",
	["BLUSH"] = "😊",
	["SMILEY"] = "😃",
	["RELAXED"] = "☺️",
	["SMIRK"] = "😏",
	["HEART_EYES"] = "😍",
	["KISSING_HEART"] = "😘",
	["KISSING_CLOSED_EYES"] = "😚",
	["FLUSHED"] = "😳",
	["RELIEVED"] = "😌",
	["SATISFIED"] = "😆",
	["GRIN"] = "😁",
	["WINK"] = "😉",
	["STUCK_OUT_TONGUE_WINKING_EYE"] = "😜",
	["STUCK_OUT_TONGUE_CLOSED_EYES"] = "😝",
	["GRINNING"] = "😀",
	["KISSING"] = "😗",
	["KISSING_SMILING_EYES"] = "😙",
	["STUCK_OUT_TONGUE"] = "😛",
	["SLEEPING"] = "😴",
	["WORRIED"] = "😟",
	["FROWNING"] = "😦",
	["ANGUISHED"] = "😧",
	["OPEN_MOUTH"] = "😮",
	["GRIMACING"] = "😬",
	["CONFUSED"] = "😕",
	["HUSHED"] = "😯",
	["EXPRESSIONLESS"] = "😑",
	["UNAMUSED"] = "😒",
	["SWEAT_SMILE"] = "😅",
	["SWEAT"] = "😓",
	["DISAPPOINTED_RELIEVED"] = "😥",
	["WEARY"] = "😩",
	["PENSIVE"] = "😔",
	["DISAPPOINTED"] = "😞",
	["CONFOUNDED"] = "😖",
	["FEARFUL"] = "😨",
	["COLD_SWEAT"] = "😰",
	["PERSEVERE"] = "😣",
	["CRY"] = "😢",
	["SOB"] = "😭",
	["JOY"] = "😂",
	["ASTONISHED"] = "😲",
	["SCREAM"] = "😱",
	["NECKBEARD"] = ":neckbeard:",
	["TIRED_FACE"] = "😫",
	["ANGRY"] = "😠",
	["RAGE"] = "😡",
	["TRIUMPH"] = "😤",
	["SLEEPY"] = "😪",
	["YUM"] = "😋",
	["MASK"] = "😷",
	["SUNGLASSES"] = "😎",
	["DIZZY_FACE"] = "😵",
	["IMP"] = "👿",
	["SMILING_IMP"] = "😈",
	["NEUTRAL_FACE"] = "😐",
	["NO_MOUTH"] = "😶",
	["INNOCENT"] = "😇",
	["ALIEN"] = "👽",
	["YELLOW_HEART"] = "💛",
	["BLUE_HEART"] = "💙",
	["PURPLE_HEART"] = "💜",
	["HEART"] = "❤️",
	["GREEN_HEART"] = "💚",
	["BROKEN_HEART"] = "💔",
	["HEARTBEAT"] = "💓",
	["HEARTPULSE"] = "💗",
	["TWO_HEARTS"] = "💕",
	["REVOLVING_HEARTS"] = "💞",
	["CUPID"] = "💘",
	["SPARKLING_HEART"] = "💖",
	["SPARKLES"] = "✨",
	["STAR"] = "⭐",
	["STAR2"] = "🌟",
	["DIZZY"] = "💫",
	["BOOM"] = "💥",
	["COLLISION"] = "💥",
	["ANGER"] = "💢",
	["EXCLAMATION"] = "❗",
	["QUESTION"] = "❓",
	["GREY_EXCLAMATION"] = "❕",
	["GREY_QUESTION"] = "❔",
	["ZZZ"] = "💤",
	["DASH"] = "💨",
	["SWEAT_DROPS"] = "💦",
	["NOTES"] = "🎶",
	["MUSICAL_NOTE"] = "🎵",
	["FIRE"] = "🔥",
	["HANKEY"] = "💩",
	["POOP"] = "💩",
	["SHIT"] = "💩",
	["+1"] = "👍",
	["THUMBSUP"] = "👍",
	["-1"] = "👎",
	["THUMBSDOWN"] = "👎",
	["OK_HAND"] = "👌",
	["PUNCH"] = "👊",
	["FACEPUNCH"] = "👊",
	["FIST"] = "✊",
	["V"] = "✌️",
	["WAVE"] = "👋",
	["HAND"] = "✋",
	["RAISED_HAND"] = "✋",
	["OPEN_HANDS"] = "👐",
	["POINT_UP"] = "☝️",
	["POINT_DOWN"] = "👇",
	["POINT_LEFT"] = "👈",
	["POINT_RIGHT"] = "👉",
	["RAISED_HANDS"] = "🙌",
	["PRAY"] = "🙏",
	["POINT_UP_2"] = "👆",
	["CLAP"] = "👏",
	["MUSCLE"] = "💪",
	["METAL"] = "🤘",
	["FU"] = "🖕",
	["WALKING"] = "🚶",
	["RUNNER"] = "🏃",
	["RUNNING"] = "🏃",
	["COUPLE"] = "👫",
	["FAMILY"] = "👪",
	["TWO_MEN_HOLDING_HANDS"] = "👬",
	["TWO_WOMEN_HOLDING_HANDS"] = "👭",
	["DANCER"] = "💃",
	["DANCERS"] = "👯",
	["OK_WOMAN"] = "🙆‍♀️",
	["NO_GOOD"] = "🙅",
	["INFORMATION_DESK_PERSON"] = "💁",
	["RAISING_HAND"] = "🙋",
	["BRIDE_WITH_VEIL"] = "👰‍♀️",
	["PERSON_WITH_POUTING_FACE"] = ":person_with_pouting_face:",
	["PERSON_FROWNING"] = ":person_frowning:",
	["BOW"] = "🙇",
	["COUPLEKISS"] = "💏",
	["COUPLE_WITH_HEART"] = "💑",
	["MASSAGE"] = "💆",
	["HAIRCUT"] = "💇",
	["NAIL_CARE"] = "💅",
	["BOY"] = "👦",
	["GIRL"] = "👧",
	["WOMAN"] = "👩",
	["MAN"] = "👨",
	["BABY"] = "👶",
	["OLDER_WOMAN"] = "👵",
	["OLDER_MAN"] = "👴",
	["PERSON_WITH_BLOND_HAIR"] = ":person_with_blond_hair:",
	["MAN_WITH_GUA_PI_MAO"] = "👲",
	["MAN_WITH_TURBAN"] = "👳‍♂️",
	["CONSTRUCTION_WORKER"] = "👷",
	["COP"] = "👮",
	["ANGEL"] = "👼",
	["PRINCESS"] = "👸",
	["SMILEY_CAT"] = "😺",
	["SMILE_CAT"] = "😸",
	["HEART_EYES_CAT"] = "😻",
	["KISSING_CAT"] = "😽",
	["SMIRK_CAT"] = "😼",
	["SCREAM_CAT"] = "🙀",
	["CRYING_CAT_FACE"] = "😿",
	["JOY_CAT"] = "😹",
	["POUTING_CAT"] = "😾",
	["JAPANESE_OGRE"] = "👹",
	["JAPANESE_GOBLIN"] = "👺",
	["SEE_NO_EVIL"] = "🙈",
	["HEAR_NO_EVIL"] = "🙉",
	["SPEAK_NO_EVIL"] = "🙊",
	["GUARDSMAN"] = "💂‍♂️",
	["SKULL"] = "💀",
	["FEET"] = "🐾",
	["LIPS"] = "👄",
	["KISS"] = "💋",
	["DROPLET"] = "💧",
	["EAR"] = "👂",
	["EYES"] = "👀",
	["NOSE"] = "👃",
	["TONGUE"] = "👅",
	["LOVE_LETTER"] = "💌",
	["BUST_IN_SILHOUETTE"] = "👤",
	["BUSTS_IN_SILHOUETTE"] = "👥",
	["SPEECH_BALLOON"] = "💬",
	["THOUGHT_BALLOON"] = "💭",
	["FEELSGOOD"] = ":feelsgood:",
	["FINNADIE"] = ":finnadie:",
	["GOBERSERK"] = ":goberserk:",
	["GODMODE"] = ":godmode:",
	["HURTREALBAD"] = ":hurtrealbad:",
	["RAGE1"] = ":rage1:",
	["RAGE2"] = ":rage2:",
	["RAGE3"] = ":rage3:",
	["RAGE4"] = ":rage4:",
	["SUSPECT"] = ":suspect:",
	["TROLLFACE"] = ":trollface:",
	["SUNNY"] = "☀️",
	["UMBRELLA"] = "☔",
	["CLOUD"] = "☁️",
	["SNOWFLAKE"] = "❄️",
	["SNOWMAN"] = "⛄",
	["ZAP"] = "⚡",
	["CYCLONE"] = "🌀",
	["FOGGY"] = "🌁",
	["OCEAN"] = "🌊",
	["CAT"] = "🐱",
	["DOG"] = "🐶",
	["MOUSE"] = "🐭",
	["HAMSTER"] = "🐹",
	["RABBIT"] = "🐰",
	["WOLF"] = "🐺",
	["FROG"] = "🐸",
	["TIGER"] = "🐯",
	["KOALA"] = "🐨",
	["BEAR"] = "🐻",
	["PIG"] = "🐷",
	["PIG_NOSE"] = "🐽",
	["COW"] = "🐮",
	["BOAR"] = "🐗",
	["MONKEY_FACE"] = "🐵",
	["MONKEY"] = "🐒",
	["HORSE"] = "🐴",
	["RACEHORSE"] = "🐎",
	["CAMEL"] = "🐫",
	["SHEEP"] = "🐑",
	["ELEPHANT"] = "🐘",
	["PANDA_FACE"] = "🐼",
	["SNAKE"] = "🐍",
	["BIRD"] = "🐦",
	["BABY_CHICK"] = "🐤",
	["HATCHED_CHICK"] = "🐥",
	["HATCHING_CHICK"] = "🐣",
	["CHICKEN"] = "🐔",
	["PENGUIN"] = "🐧",
	["TURTLE"] = "🐢",
	["BUG"] = "🐛",
	["HONEYBEE"] = "🐝",
	["ANT"] = "🐜",
	["BEETLE"] = "🪲",
	["SNAIL"] = "🐌",
	["OCTOPUS"] = "🐙",
	["TROPICAL_FISH"] = "🐠",
	["FISH"] = "🐟",
	["WHALE"] = "🐳",
	["WHALE2"] = "🐋",
	["DOLPHIN"] = "🐬",
	["COW2"] = "🐄",
	["RAM"] = "🐏",
	["RAT"] = "🐀",
	["WATER_BUFFALO"] = "🐃",
	["TIGER2"] = "🐅",
	["RABBIT2"] = "🐇",
	["DRAGON"] = "🐉",
	["GOAT"] = "🐐",
	["ROOSTER"] = "🐓",
	["DOG2"] = "🐕",
	["PIG2"] = "🐖",
	["MOUSE2"] = "🐁",
	["OX"] = "🐂",
	["DRAGON_FACE"] = "🐲",
	["BLOWFISH"] = "🐡",
	["CROCODILE"] = "🐊",
	["DROMEDARY_CAMEL"] = "🐪",
	["LEOPARD"] = "🐆",
	["CAT2"] = "🐈",
	["POODLE"] = "🐩",
	["PAW_PRINTS"] = "🐾",
	["BOUQUET"] = "💐",
	["CHERRY_BLOSSOM"] = "🌸",
	["TULIP"] = "🌷",
	["FOUR_LEAF_CLOVER"] = "🍀",
	["ROSE"] = "🌹",
	["SUNFLOWER"] = "🌻",
	["HIBISCUS"] = "🌺",
	["MAPLE_LEAF"] = "🍁",
	["LEAVES"] = "🍃",
	["FALLEN_LEAF"] = "🍂",
	["HERB"] = "🌿",
	["MUSHROOM"] = "🍄",
	["CACTUS"] = "🌵",
	["PALM_TREE"] = "🌴",
	["EVERGREEN_TREE"] = "🌲",
	["DECIDUOUS_TREE"] = "🌳",
	["CHESTNUT"] = "🌰",
	["SEEDLING"] = "🌱",
	["BLOSSOM"] = "🌼",
	["EAR_OF_RICE"] = "🌾",
	["SHELL"] = "🐚",
	["GLOBE_WITH_MERIDIANS"] = "🌐",
	["SUN_WITH_FACE"] = "🌞",
	["FULL_MOON_WITH_FACE"] = "🌝",
	["NEW_MOON_WITH_FACE"] = "🌚",
	["NEW_MOON"] = "🌑",
	["WAXING_CRESCENT_MOON"] = "🌒",
	["FIRST_QUARTER_MOON"] = "🌓",
	["WAXING_GIBBOUS_MOON"] = "🌔",
	["FULL_MOON"] = "🌕",
	["WANING_GIBBOUS_MOON"] = "🌖",
	["LAST_QUARTER_MOON"] = "🌗",
	["WANING_CRESCENT_MOON"] = "🌘",
	["LAST_QUARTER_MOON_WITH_FACE"] = "🌜",
	["FIRST_QUARTER_MOON_WITH_FACE"] = "🌛",
	["MOON"] = "🌔",
	["EARTH_AFRICA"] = "🌍",
	["EARTH_AMERICAS"] = "🌎",
	["EARTH_ASIA"] = "🌏",
	["VOLCANO"] = "🌋",
	["MILKY_WAY"] = "🌌",
	["PARTLY_SUNNY"] = "⛅",
	["OCTOCAT"] = ":octocat:",
	["SQUIRREL"] = ":squirrel:",
	["BAMBOO"] = "🎍",
	["GIFT_HEART"] = "💝",
	["DOLLS"] = "🎎",
	["SCHOOL_SATCHEL"] = "🎒",
	["MORTAR_BOARD"] = "🎓",
	["FLAGS"] = "🎏",
	["FIREWORKS"] = "🎆",
	["SPARKLER"] = "🎇",
	["WIND_CHIME"] = "🎐",
	["RICE_SCENE"] = "🎑",
	["JACK_O_LANTERN"] = "🎃",
	["GHOST"] = "👻",
	["SANTA"] = "🎅",
	["CHRISTMAS_TREE"] = "🎄",
	["GIFT"] = "🎁",
	["BELL"] = "🔔",
	["NO_BELL"] = "🔕",
	["TANABATA_TREE"] = "🎋",
	["TADA"] = "🎉",
	["CONFETTI_BALL"] = "🎊",
	["BALLOON"] = "🎈",
	["CRYSTAL_BALL"] = "🔮",
	["CD"] = "💿",
	["DVD"] = "📀",
	["FLOPPY_DISK"] = "💾",
	["CAMERA"] = "📷",
	["VIDEO_CAMERA"] = "📹",
	["MOVIE_CAMERA"] = "🎥",
	["COMPUTER"] = "💻",
	["TV"] = "📺",
	["IPHONE"] = "📱",
	["PHONE"] = "☎️",
	["TELEPHONE"] = "☎️",
	["TELEPHONE_RECEIVER"] = "📞",
	["PAGER"] = "📟",
	["FAX"] = "📠",
	["MINIDISC"] = "💽",
	["VHS"] = "📼",
	["SOUND"] = "🔉",
	["SPEAKER"] = "🔈",
	["MUTE"] = "🔇",
	["LOUDSPEAKER"] = "📢",
	["MEGA"] = "📣",
	["HOURGLASS"] = "⌛",
	["HOURGLASS_FLOWING_SAND"] = "⏳",
	["ALARM_CLOCK"] = "⏰",
	["WATCH"] = "⌚",
	["RADIO"] = "📻",
	["SATELLITE"] = "📡",
	["LOOP"] = "➿",
	["MAG"] = "🔍",
	["MAG_RIGHT"] = "🔎",
	["UNLOCK"] = "🔓",
	["LOCK"] = "🔒",
	["LOCK_WITH_INK_PEN"] = "🔏",
	["CLOSED_LOCK_WITH_KEY"] = "🔐",
	["KEY"] = "🔑",
	["BULB"] = "💡",
	["FLASHLIGHT"] = "🔦",
	["HIGH_BRIGHTNESS"] = "🔆",
	["LOW_BRIGHTNESS"] = "🔅",
	["ELECTRIC_PLUG"] = "🔌",
	["BATTERY"] = "🔋",
	["CALLING"] = "📲",
	["EMAIL"] = "📧",
	["MAILBOX"] = "📫",
	["POSTBOX"] = "📮",
	["BATH"] = "🛀",
	["BATHTUB"] = "🛁",
	["SHOWER"] = "🚿",
	["TOILET"] = "🚽",
	["WRENCH"] = "🔧",
	["NUT_AND_BOLT"] = "🔩",
	["HAMMER"] = "🔨",
	["SEAT"] = "💺",
	["MONEYBAG"] = "💰",
	["YEN"] = "💴",
	["DOLLAR"] = "💵",
	["POUND"] = "💷",
	["EURO"] = "💶",
	["CREDIT_CARD"] = "💳",
	["MONEY_WITH_WINGS"] = "💸",
	["E-MAIL"] = "📧",
	["INBOX_TRAY"] = "📥",
	["OUTBOX_TRAY"] = "📤",
	["ENVELOPE"] = "✉️",
	["INCOMING_ENVELOPE"] = "📨",
	["POSTAL_HORN"] = "📯",
	["MAILBOX_CLOSED"] = "📪",
	["MAILBOX_WITH_MAIL"] = "📬",
	["MAILBOX_WITH_NO_MAIL"] = "📭",
	["DOOR"] = "🚪",
	["SMOKING"] = "🚬",
	["BOMB"] = "💣",
	["GUN"] = "🔫",
	["HOCHO"] = "🔪",
	["PILL"] = "💊",
	["SYRINGE"] = "💉",
	["PAGE_FACING_UP"] = "📄",
	["PAGE_WITH_CURL"] = "📃",
	["BOOKMARK_TABS"] = "📑",
	["BAR_CHART"] = "📊",
	["CHART_WITH_UPWARDS_TREND"] = "📈",
	["CHART_WITH_DOWNWARDS_TREND"] = "📉",
	["SCROLL"] = "📜",
	["CLIPBOARD"] = "📋",
	["CALENDAR"] = "📆",
	["DATE"] = "📅",
	["CARD_INDEX"] = "📇",
	["FILE_FOLDER"] = "📁",
	["OPEN_FILE_FOLDER"] = "📂",
	["SCISSORS"] = "✂️",
	["PUSHPIN"] = "📌",
	["PAPERCLIP"] = "📎",
	["BLACK_NIB"] = "✒️",
	["PENCIL2"] = "✏️",
	["STRAIGHT_RULER"] = "📏",
	["TRIANGULAR_RULER"] = "📐",
	["CLOSED_BOOK"] = "📕",
	["GREEN_BOOK"] = "📗",
	["BLUE_BOOK"] = "📘",
	["ORANGE_BOOK"] = "📙",
	["NOTEBOOK"] = "📓",
	["NOTEBOOK_WITH_DECORATIVE_COVER"] = "📔",
	["LEDGER"] = "📒",
	["BOOKS"] = "📚",
	["BOOKMARK"] = "🔖",
	["NAME_BADGE"] = "📛",
	["MICROSCOPE"] = "🔬",
	["TELESCOPE"] = "🔭",
	["NEWSPAPER"] = "📰",
	["FOOTBALL"] = "🏈",
	["BASKETBALL"] = "🏀",
	["SOCCER"] = "⚽",
	["BASEBALL"] = "⚾",
	["TENNIS"] = "🎾",
	["8BALL"] = "🎱",
	["RUGBY_FOOTBALL"] = "🏉",
	["BOWLING"] = "🎳",
	["GOLF"] = "⛳",
	["MOUNTAIN_BICYCLIST"] = "🚵",
	["BICYCLIST"] = "🚴",
	["HORSE_RACING"] = "🏇",
	["SNOWBOARDER"] = "🏂",
	["SWIMMER"] = "🏊",
	["SURFER"] = "🏄",
	["SKI"] = "🎿",
	["SPADES"] = "♠️",
	["HEARTS"] = "♥️",
	["CLUBS"] = "♣️",
	["DIAMONDS"] = "♦️",
	["GEM"] = "💎",
	["RING"] = "💍",
	["TROPHY"] = "🏆",
	["MUSICAL_SCORE"] = "🎼",
	["MUSICAL_KEYBOARD"] = "🎹",
	["VIOLIN"] = "🎻",
	["SPACE_INVADER"] = "👾",
	["VIDEO_GAME"] = "🎮",
	["BLACK_JOKER"] = "🃏",
	["FLOWER_PLAYING_CARDS"] = "🎴",
	["GAME_DIE"] = "🎲",
	["DART"] = "🎯",
	["MAHJONG"] = "🀄",
	["CLAPPER"] = "🎬",
	["MEMO"] = "📝",
	["PENCIL"] = "📝",
	["BOOK"] = "📖",
	["ART"] = "🎨",
	["MICROPHONE"] = "🎤",
	["HEADPHONES"] = "🎧",
	["TRUMPET"] = "🎺",
	["SAXOPHONE"] = "🎷",
	["GUITAR"] = "🎸",
	["SHOE"] = "👞",
	["SANDAL"] = "👡",
	["HIGH_HEEL"] = "👠",
	["LIPSTICK"] = "💄",
	["BOOT"] = "👢",
	["SHIRT"] = "👕",
	["TSHIRT"] = "👕",
	["NECKTIE"] = "👔",
	["WOMANS_CLOTHES"] = "👚",
	["DRESS"] = "👗",
	["RUNNING_SHIRT_WITH_SASH"] = "🎽",
	["JEANS"] = "👖",
	["KIMONO"] = "👘",
	["BIKINI"] = "👙",
	["RIBBON"] = "🎀",
	["TOPHAT"] = "🎩",
	["CROWN"] = "👑",
	["WOMANS_HAT"] = "👒",
	["MANS_SHOE"] = "👞",
	["CLOSED_UMBRELLA"] = "🌂",
	["BRIEFCASE"] = "💼",
	["HANDBAG"] = "👜",
	["POUCH"] = "👝",
	["PURSE"] = "👛",
	["EYEGLASSES"] = "👓",
	["FISHING_POLE_AND_FISH"] = "🎣",
	["COFFEE"] = "☕",
	["TEA"] = "🍵",
	["SAKE"] = "🍶",
	["BABY_BOTTLE"] = "🍼",
	["BEER"] = "🍺",
	["BEERS"] = "🍻",
	["COCKTAIL"] = "🍸",
	["TROPICAL_DRINK"] = "🍹",
	["WINE_GLASS"] = "🍷",
	["FORK_AND_KNIFE"] = "🍴",
	["PIZZA"] = "🍕",
	["HAMBURGER"] = "🍔",
	["FRIES"] = "🍟",
	["POULTRY_LEG"] = "🍗",
	["MEAT_ON_BONE"] = "🍖",
	["SPAGHETTI"] = "🍝",
	["CURRY"] = "🍛",
	["FRIED_SHRIMP"] = "🍤",
	["BENTO"] = "🍱",
	["SUSHI"] = "🍣",
	["FISH_CAKE"] = "🍥",
	["RICE_BALL"] = "🍙",
	["RICE_CRACKER"] = "🍘",
	["RICE"] = "🍚",
	["RAMEN"] = "🍜",
	["STEW"] = "🍲",
	["ODEN"] = "🍢",
	["DANGO"] = "🍡",
	["EGG"] = "🥚",
	["BREAD"] = "🍞",
	["DOUGHNUT"] = "🍩",
	["CUSTARD"] = "🍮",
	["ICECREAM"] = "🍦",
	["ICE_CREAM"] = "🍨",
	["SHAVED_ICE"] = "🍧",
	["BIRTHDAY"] = "🎂",
	["CAKE"] = "🍰",
	["COOKIE"] = "🍪",
	["CHOCOLATE_BAR"] = "🍫",
	["CANDY"] = "🍬",
	["LOLLIPOP"] = "🍭",
	["HONEY_POT"] = "🍯",
	["APPLE"] = "🍎",
	["GREEN_APPLE"] = "🍏",
	["TANGERINE"] = "🍊",
	["LEMON"] = "🍋",
	["CHERRIES"] = "🍒",
	["GRAPES"] = "🍇",
	["WATERMELON"] = "🍉",
	["STRAWBERRY"] = "🍓",
	["PEACH"] = "🍑",
	["MELON"] = "🍈",
	["BANANA"] = "🍌",
	["PEAR"] = "🍐",
	["PINEAPPLE"] = "🍍",
	["SWEET_POTATO"] = "🍠",
	["EGGPLANT"] = "🍆",
	["TOMATO"] = "🍅",
	["CORN"] = "🌽",
	["HOUSE"] = "🏠",
	["HOUSE_WITH_GARDEN"] = "🏡",
	["SCHOOL"] = "🏫",
	["OFFICE"] = "🏢",
	["POST_OFFICE"] = "🏣",
	["HOSPITAL"] = "🏥",
	["BANK"] = "🏦",
	["CONVENIENCE_STORE"] = "🏪",
	["LOVE_HOTEL"] = "🏩",
	["HOTEL"] = "🏨",
	["WEDDING"] = "💒",
	["CHURCH"] = "⛪",
	["DEPARTMENT_STORE"] = "🏬",
	["EUROPEAN_POST_OFFICE"] = "🏤",
	["CITY_SUNRISE"] = "🌇",
	["CITY_SUNSET"] = "🌆",
	["JAPANESE_CASTLE"] = "🏯",
	["EUROPEAN_CASTLE"] = "🏰",
	["TENT"] = "⛺",
	["FACTORY"] = "🏭",
	["TOKYO_TOWER"] = "🗼",
	["JAPAN"] = "🗾",
	["MOUNT_FUJI"] = "🗻",
	["SUNRISE_OVER_MOUNTAINS"] = "🌄",
	["SUNRISE"] = "🌅",
	["STARS"] = "🌠",
	["STATUE_OF_LIBERTY"] = "🗽",
	["BRIDGE_AT_NIGHT"] = "🌉",
	["CAROUSEL_HORSE"] = "🎠",
	["RAINBOW"] = "🌈",
	["FERRIS_WHEEL"] = "🎡",
	["FOUNTAIN"] = "⛲",
	["ROLLER_COASTER"] = "🎢",
	["SHIP"] = "🚢",
	["SPEEDBOAT"] = "🚤",
	["BOAT"] = "⛵",
	["SAILBOAT"] = "⛵",
	["ROWBOAT"] = "🚣",
	["ANCHOR"] = "⚓",
	["ROCKET"] = "🚀",
	["AIRPLANE"] = "✈️",
	["HELICOPTER"] = "🚁",
	["STEAM_LOCOMOTIVE"] = "🚂",
	["TRAM"] = "🚊",
	["MOUNTAIN_RAILWAY"] = "🚞",
	["BIKE"] = "🚲",
	["AERIAL_TRAMWAY"] = "🚡",
	["SUSPENSION_RAILWAY"] = "🚟",
	["MOUNTAIN_CABLEWAY"] = "🚠",
	["TRACTOR"] = "🚜",
	["BLUE_CAR"] = "🚙",
	["ONCOMING_AUTOMOBILE"] = "🚘",
	["CAR"] = "🚗",
	["RED_CAR"] = "🚗",
	["TAXI"] = "🚕",
	["ONCOMING_TAXI"] = "🚖",
	["ARTICULATED_LORRY"] = "🚛",
	["BUS"] = "🚌",
	["ONCOMING_BUS"] = "🚍",
	["ROTATING_LIGHT"] = "🚨",
	["POLICE_CAR"] = "🚓",
	["ONCOMING_POLICE_CAR"] = "🚔",
	["FIRE_ENGINE"] = "🚒",
	["AMBULANCE"] = "🚑",
	["MINIBUS"] = "🚐",
	["TRUCK"] = "🚚",
	["TRAIN"] = "🚋",
	["STATION"] = "🚉",
	["TRAIN2"] = "🚆",
	["BULLETTRAIN_FRONT"] = "🚅",
	["BULLETTRAIN_SIDE"] = "🚄",
	["LIGHT_RAIL"] = "🚈",
	["MONORAIL"] = "🚝",
	["RAILWAY_CAR"] = "🚃",
	["TROLLEYBUS"] = "🚎",
	["TICKET"] = "🎫",
	["FUELPUMP"] = "⛽",
	["VERTICAL_TRAFFIC_LIGHT"] = "🚦",
	["TRAFFIC_LIGHT"] = "🚥",
	["WARNING"] = "⚠️",
	["CONSTRUCTION"] = "🚧",
	["BEGINNER"] = "🔰",
	["ATM"] = "🏧",
	["SLOT_MACHINE"] = "🎰",
	["BUSSTOP"] = "🚏",
	["BARBER"] = "💈",
	["HOTSPRINGS"] = "♨️",
	["CHECKERED_FLAG"] = "🏁",
	["CROSSED_FLAGS"] = "🎌",
	["IZAKAYA_LANTERN"] = "🏮",
	["MOYAI"] = "🗿",
	["CIRCUS_TENT"] = "🎪",
	["PERFORMING_ARTS"] = "🎭",
	["ROUND_PUSHPIN"] = "📍",
	["TRIANGULAR_FLAG_ON_POST"] = "🚩",
	["JP"] = "🇯🇵",
	["KR"] = "🇰🇷",
	["CN"] = "🇨🇳",
	["US"] = "🇺🇸",
	["FR"] = "🇫🇷",
	["ES"] = "🇪🇸",
	["IT"] = "🇮🇹",
	["RU"] = "🇷🇺",
	["GB"] = "🇬🇧",
	["UK"] = "🇬🇧",
	["DE"] = "🇩🇪",
	["ONE"] = "1️⃣",
	["TWO"] = "2️⃣",
	["THREE"] = "3️⃣",
	["FOUR"] = "4️⃣",
	["FIVE"] = "5️⃣",
	["SIX"] = "6️⃣",
	["SEVEN"] = "7️⃣",
	["EIGHT"] = "8️⃣",
	["NINE"] = "9️⃣",
	["KEYCAP_TEN"] = "🔟",
	["1234"] = "🔢",
	["ZERO"] = "0️⃣",
	["HASH"] = "#️⃣",
	["SYMBOLS"] = "🔣",
	["ARROW_BACKWARD"] = "◀️",
	["ARROW_DOWN"] = "⬇️",
	["ARROW_FORWARD"] = "▶️",
	["ARROW_LEFT"] = "⬅️",
	["CAPITAL_ABCD"] = "🔠",
	["ABCD"] = "🔡",
	["ABC"] = "🔤",
	["ARROW_LOWER_LEFT"] = "↙️",
	["ARROW_LOWER_RIGHT"] = "↘️",
	["ARROW_RIGHT"] = "➡️",
	["ARROW_UP"] = "⬆️",
	["ARROW_UPPER_LEFT"] = "↖️",
	["ARROW_UPPER_RIGHT"] = "↗️",
	["ARROW_DOUBLE_DOWN"] = "⏬",
	["ARROW_DOUBLE_UP"] = "⏫",
	["ARROW_DOWN_SMALL"] = "🔽",
	["ARROW_HEADING_DOWN"] = "⤵️",
	["ARROW_HEADING_UP"] = "⤴️",
	["LEFTWARDS_ARROW_WITH_HOOK"] = "↩️",
	["ARROW_RIGHT_HOOK"] = "↪️",
	["LEFT_RIGHT_ARROW"] = "↔️",
	["ARROW_UP_DOWN"] = "↕️",
	["ARROW_UP_SMALL"] = "🔼",
	["ARROWS_CLOCKWISE"] = "🔃",
	["ARROWS_COUNTERCLOCKWISE"] = "🔄",
	["REWIND"] = "⏪",
	["FAST_FORWARD"] = "⏩",
	["INFORMATION_SOURCE"] = "ℹ️",
	["OK"] = "🆗",
	["TWISTED_RIGHTWARDS_ARROWS"] = "🔀",
	["REPEAT"] = "🔁",
	["REPEAT_ONE"] = "🔂",
	["NEW"] = "🆕",
	["TOP"] = "🔝",
	["UP"] = "🆙",
	["COOL"] = "🆒",
	["FREE"] = "🆓",
	["NG"] = "🆖",
	["CINEMA"] = "🎦",
	["KOKO"] = "🈁",
	["SIGNAL_STRENGTH"] = "📶",
	["U5272"] = "🈹",
	["U5408"] = "🈴",
	["U55B6"] = "🈺",
	["U6307"] = "🈯",
	["U6708"] = "🈷️",
	["U6709"] = "🈶",
	["U6E80"] = "🈵",
	["U7121"] = "🈚",
	["U7533"] = "🈸",
	["U7A7A"] = "🈳",
	["U7981"] = "🈲",
	["SA"] = "🈂️",
	["RESTROOM"] = "🚻",
	["MENS"] = "🚹",
	["WOMENS"] = "🚺",
	["BABY_SYMBOL"] = "🚼",
	["NO_SMOKING"] = "🚭",
	["PARKING"] = "🅿️",
	["WHEELCHAIR"] = "♿",
	["METRO"] = "🚇",
	["BAGGAGE_CLAIM"] = "🛄",
	["ACCEPT"] = "🉑",
	["WC"] = "🚾",
	["POTABLE_WATER"] = "🚰",
	["PUT_LITTER_IN_ITS_PLACE"] = "🚮",
	["SECRET"] = "㊙️",
	["CONGRATULATIONS"] = "㊗️",
	["M"] = "Ⓜ️",
	["PASSPORT_CONTROL"] = "🛂",
	["LEFT_LUGGAGE"] = "🛅",
	["CUSTOMS"] = "🛃",
	["IDEOGRAPH_ADVANTAGE"] = "🉐",
	["CL"] = "🆑",
	["SOS"] = "🆘",
	["ID"] = "🆔",
	["NO_ENTRY_SIGN"] = "🚫",
	["UNDERAGE"] = "🔞",
	["NO_MOBILE_PHONES"] = "📵",
	["DO_NOT_LITTER"] = "🚯",
	["NON-POTABLE_WATER"] = "🚱",
	["NO_BICYCLES"] = "🚳",
	["NO_PEDESTRIANS"] = "🚷",
	["CHILDREN_CROSSING"] = "🚸",
	["NO_ENTRY"] = "⛔",
	["EIGHT_SPOKED_ASTERISK"] = "✳️",
	["EIGHT_POINTED_BLACK_STAR"] = "✴️",
	["HEART_DECORATION"] = "💟",
	["VS"] = "🆚",
	["VIBRATION_MODE"] = "📳",
	["MOBILE_PHONE_OFF"] = "📴",
	["CHART"] = "💹",
	["CURRENCY_EXCHANGE"] = "💱",
	["ARIES"] = "♈",
	["TAURUS"] = "♉",
	["GEMINI"] = "♊",
	["CANCER"] = "♋",
	["LEO"] = "♌",
	["VIRGO"] = "♍",
	["LIBRA"] = "♎",
	["SCORPIUS"] = "♏",
	["SAGITTARIUS"] = "♐",
	["CAPRICORN"] = "♑",
	["AQUARIUS"] = "♒",
	["PISCES"] = "♓",
	["OPHIUCHUS"] = "⛎",
	["SIX_POINTED_STAR"] = "🔯",
	["NEGATIVE_SQUARED_CROSS_MARK"] = "❎",
	["A"] = "🅰️",
	["B"] = "🅱️",
	["AB"] = "🆎",
	["O2"] = "🅾️",
	["DIAMOND_SHAPE_WITH_A_DOT_INSIDE"] = "💠",
	["RECYCLE"] = "♻️",
	["END"] = "🔚",
	["ON"] = "🔛",
	["SOON"] = "🔜",
	["CLOCK1"] = "🕐",
	["CLOCK130"] = "🕜",
	["CLOCK10"] = "🕙",
	["CLOCK1030"] = "🕥",
	["CLOCK11"] = "🕚",
	["CLOCK1130"] = "🕦",
	["CLOCK12"] = "🕛",
	["CLOCK1230"] = "🕧",
	["CLOCK2"] = "🕑",
	["CLOCK230"] = "🕝",
	["CLOCK3"] = "🕒",
	["CLOCK330"] = "🕞",
	["CLOCK4"] = "🕓",
	["CLOCK430"] = "🕟",
	["CLOCK5"] = "🕔",
	["CLOCK530"] = "🕠",
	["CLOCK6"] = "🕕",
	["CLOCK630"] = "🕡",
	["CLOCK7"] = "🕖",
	["CLOCK730"] = "🕢",
	["CLOCK8"] = "🕗",
	["CLOCK830"] = "🕣",
	["CLOCK9"] = "🕘",
	["CLOCK930"] = "🕤",
	["HEAVY_DOLLAR_SIGN"] = "💲",
	["COPYRIGHT"] = "©️",
	["REGISTERED"] = "®️",
	["TM"] = "™️",
	["X"] = "❌",
	["HEAVY_EXCLAMATION_MARK"] = "❗",
	["BANGBANG"] = "‼️",
	["INTERROBANG"] = "⁉️",
	["O"] = "⭕",
	["HEAVY_MULTIPLICATION_X"] = "✖️",
	["HEAVY_PLUS_SIGN"] = "➕",
	["HEAVY_MINUS_SIGN"] = "➖",
	["HEAVY_DIVISION_SIGN"] = "➗",
	["WHITE_FLOWER"] = "💮",
	["100"] = "💯",
	["HEAVY_CHECK_MARK"] = "✔️",
	["BALLOT_BOX_WITH_CHECK"] = "☑️",
	["RADIO_BUTTON"] = "🔘",
	["LINK"] = "🔗",
	["CURLY_LOOP"] = "➰",
	["WAVY_DASH"] = "〰️",
	["PART_ALTERNATION_MARK"] = "〽️",
	["TRIDENT"] = "🔱",
	["BLACK_SQUARE"] = ":black_square:",
	["WHITE_SQUARE"] = ":white_square:",
	["WHITE_CHECK_MARK"] = "✅",
	["BLACK_SQUARE_BUTTON"] = "🔲",
	["WHITE_SQUARE_BUTTON"] = "🔳",
	["BLACK_CIRCLE"] = "⚫",
	["WHITE_CIRCLE"] = "⚪",
	["RED_CIRCLE"] = "🔴",
	["LARGE_BLUE_CIRCLE"] = "🔵",
	["LARGE_BLUE_DIAMOND"] = "🔷",
	["LARGE_ORANGE_DIAMOND"] = "🔶",
	["SMALL_BLUE_DIAMOND"] = "🔹",
	["SMALL_ORANGE_DIAMOND"] = "🔸",
	["SMALL_RED_TRIANGLE"] = "🔺",
	["SMALL_RED_TRIANGLE_DOWN"] = "🔻",
	["SHIPIT"] = ":shipit:",
}

local function to_count(v)
	if type(v) == "number" then
		return math.floor(v)
	end
	return 0
end

local function normalize_key(key)
	local raw = tostring(key or "")
	local trimmed = raw:gsub("^:+", ""):gsub(":+$", "")
	trimmed = trimmed:gsub("%s+", "_")
	local upper = trimmed:upper()
	return upper, trimmed:lower()
end

function M.format_line(reactions, my_reactions)
	if type(reactions) ~= "table" then
		return nil
	end

	local items = {}
	for key, value in pairs(reactions) do
		local count = to_count(value)
		if count > 0 then
			table.insert(items, { key = tostring(key), count = count })
		end
	end

	if #items == 0 then
		return nil
	end

	table.sort(items, function(a, b)
		if a.count ~= b.count then
			return a.count > b.count
		end
		return a.key < b.key
	end)

	local chunks = {}
	for _, item in ipairs(items) do
		local mine = type(my_reactions) == "table" and my_reactions[string.upper(item.key)]
		local upper, fallback = normalize_key(item.key)
		local label = emoji_map[upper] or (":" .. fallback .. ":")
				if mine then
			table.insert(chunks, string.format("%s %d (you)", label, item.count))
		else
			table.insert(chunks, string.format("%s %d", label, item.count))
		end
	end

	return table.concat(chunks, "  ")
end


function M.render_choice(choice)
	local upper, fallback = normalize_key(choice)
	local symbol = emoji_map[upper] or (":" .. fallback .. ":")
	return string.format("%s  %s", symbol, upper)
end

M.all_reaction_choices = {
	"BOWTIE",
	"SMILE",
	"LAUGHING",
	"BLUSH",
	"SMILEY",
	"RELAXED",
	"SMIRK",
	"HEART_EYES",
	"KISSING_HEART",
	"KISSING_CLOSED_EYES",
	"FLUSHED",
	"RELIEVED",
	"SATISFIED",
	"GRIN",
	"WINK",
	"STUCK_OUT_TONGUE_WINKING_EYE",
	"STUCK_OUT_TONGUE_CLOSED_EYES",
	"GRINNING",
	"KISSING",
	"KISSING_SMILING_EYES",
	"STUCK_OUT_TONGUE",
	"SLEEPING",
	"WORRIED",
	"FROWNING",
	"ANGUISHED",
	"OPEN_MOUTH",
	"GRIMACING",
	"CONFUSED",
	"HUSHED",
	"EXPRESSIONLESS",
	"UNAMUSED",
	"SWEAT_SMILE",
	"SWEAT",
	"DISAPPOINTED_RELIEVED",
	"WEARY",
	"PENSIVE",
	"DISAPPOINTED",
	"CONFOUNDED",
	"FEARFUL",
	"COLD_SWEAT",
	"PERSEVERE",
	"CRY",
	"SOB",
	"JOY",
	"ASTONISHED",
	"SCREAM",
	"NECKBEARD",
	"TIRED_FACE",
	"ANGRY",
	"RAGE",
	"TRIUMPH",
	"SLEEPY",
	"YUM",
	"MASK",
	"SUNGLASSES",
	"DIZZY_FACE",
	"IMP",
	"SMILING_IMP",
	"NEUTRAL_FACE",
	"NO_MOUTH",
	"INNOCENT",
	"ALIEN",
	"YELLOW_HEART",
	"BLUE_HEART",
	"PURPLE_HEART",
	"HEART",
	"GREEN_HEART",
	"BROKEN_HEART",
	"HEARTBEAT",
	"HEARTPULSE",
	"TWO_HEARTS",
	"REVOLVING_HEARTS",
	"CUPID",
	"SPARKLING_HEART",
	"SPARKLES",
	"STAR",
	"STAR2",
	"DIZZY",
	"BOOM",
	"COLLISION",
	"ANGER",
	"EXCLAMATION",
	"QUESTION",
	"GREY_EXCLAMATION",
	"GREY_QUESTION",
	"ZZZ",
	"DASH",
	"SWEAT_DROPS",
	"NOTES",
	"MUSICAL_NOTE",
	"FIRE",
	"HANKEY",
	"POOP",
	"SHIT",
	"+1",
	"THUMBSUP",
	"-1",
	"THUMBSDOWN",
	"OK_HAND",
	"PUNCH",
	"FACEPUNCH",
	"FIST",
	"V",
	"WAVE",
	"HAND",
	"RAISED_HAND",
	"OPEN_HANDS",
	"POINT_UP",
	"POINT_DOWN",
	"POINT_LEFT",
	"POINT_RIGHT",
	"RAISED_HANDS",
	"PRAY",
	"POINT_UP_2",
	"CLAP",
	"MUSCLE",
	"METAL",
	"FU",
	"WALKING",
	"RUNNER",
	"RUNNING",
	"COUPLE",
	"FAMILY",
	"TWO_MEN_HOLDING_HANDS",
	"TWO_WOMEN_HOLDING_HANDS",
	"DANCER",
	"DANCERS",
	"OK_WOMAN",
	"NO_GOOD",
	"INFORMATION_DESK_PERSON",
	"RAISING_HAND",
	"BRIDE_WITH_VEIL",
	"PERSON_WITH_POUTING_FACE",
	"PERSON_FROWNING",
	"BOW",
	"COUPLEKISS",
	"COUPLE_WITH_HEART",
	"MASSAGE",
	"HAIRCUT",
	"NAIL_CARE",
	"BOY",
	"GIRL",
	"WOMAN",
	"MAN",
	"BABY",
	"OLDER_WOMAN",
	"OLDER_MAN",
	"PERSON_WITH_BLOND_HAIR",
	"MAN_WITH_GUA_PI_MAO",
	"MAN_WITH_TURBAN",
	"CONSTRUCTION_WORKER",
	"COP",
	"ANGEL",
	"PRINCESS",
	"SMILEY_CAT",
	"SMILE_CAT",
	"HEART_EYES_CAT",
	"KISSING_CAT",
	"SMIRK_CAT",
	"SCREAM_CAT",
	"CRYING_CAT_FACE",
	"JOY_CAT",
	"POUTING_CAT",
	"JAPANESE_OGRE",
	"JAPANESE_GOBLIN",
	"SEE_NO_EVIL",
	"HEAR_NO_EVIL",
	"SPEAK_NO_EVIL",
	"GUARDSMAN",
	"SKULL",
	"FEET",
	"LIPS",
	"KISS",
	"DROPLET",
	"EAR",
	"EYES",
	"NOSE",
	"TONGUE",
	"LOVE_LETTER",
	"BUST_IN_SILHOUETTE",
	"BUSTS_IN_SILHOUETTE",
	"SPEECH_BALLOON",
	"THOUGHT_BALLOON",
	"FEELSGOOD",
	"FINNADIE",
	"GOBERSERK",
	"GODMODE",
	"HURTREALBAD",
	"RAGE1",
	"RAGE2",
	"RAGE3",
	"RAGE4",
	"SUSPECT",
	"TROLLFACE",
	"SUNNY",
	"UMBRELLA",
	"CLOUD",
	"SNOWFLAKE",
	"SNOWMAN",
	"ZAP",
	"CYCLONE",
	"FOGGY",
	"OCEAN",
	"CAT",
	"DOG",
	"MOUSE",
	"HAMSTER",
	"RABBIT",
	"WOLF",
	"FROG",
	"TIGER",
	"KOALA",
	"BEAR",
	"PIG",
	"PIG_NOSE",
	"COW",
	"BOAR",
	"MONKEY_FACE",
	"MONKEY",
	"HORSE",
	"RACEHORSE",
	"CAMEL",
	"SHEEP",
	"ELEPHANT",
	"PANDA_FACE",
	"SNAKE",
	"BIRD",
	"BABY_CHICK",
	"HATCHED_CHICK",
	"HATCHING_CHICK",
	"CHICKEN",
	"PENGUIN",
	"TURTLE",
	"BUG",
	"HONEYBEE",
	"ANT",
	"BEETLE",
	"SNAIL",
	"OCTOPUS",
	"TROPICAL_FISH",
	"FISH",
	"WHALE",
	"WHALE2",
	"DOLPHIN",
	"COW2",
	"RAM",
	"RAT",
	"WATER_BUFFALO",
	"TIGER2",
	"RABBIT2",
	"DRAGON",
	"GOAT",
	"ROOSTER",
	"DOG2",
	"PIG2",
	"MOUSE2",
	"OX",
	"DRAGON_FACE",
	"BLOWFISH",
	"CROCODILE",
	"DROMEDARY_CAMEL",
	"LEOPARD",
	"CAT2",
	"POODLE",
	"PAW_PRINTS",
	"BOUQUET",
	"CHERRY_BLOSSOM",
	"TULIP",
	"FOUR_LEAF_CLOVER",
	"ROSE",
	"SUNFLOWER",
	"HIBISCUS",
	"MAPLE_LEAF",
	"LEAVES",
	"FALLEN_LEAF",
	"HERB",
	"MUSHROOM",
	"CACTUS",
	"PALM_TREE",
	"EVERGREEN_TREE",
	"DECIDUOUS_TREE",
	"CHESTNUT",
	"SEEDLING",
	"BLOSSOM",
	"EAR_OF_RICE",
	"SHELL",
	"GLOBE_WITH_MERIDIANS",
	"SUN_WITH_FACE",
	"FULL_MOON_WITH_FACE",
	"NEW_MOON_WITH_FACE",
	"NEW_MOON",
	"WAXING_CRESCENT_MOON",
	"FIRST_QUARTER_MOON",
	"WAXING_GIBBOUS_MOON",
	"FULL_MOON",
	"WANING_GIBBOUS_MOON",
	"LAST_QUARTER_MOON",
	"WANING_CRESCENT_MOON",
	"LAST_QUARTER_MOON_WITH_FACE",
	"FIRST_QUARTER_MOON_WITH_FACE",
	"MOON",
	"EARTH_AFRICA",
	"EARTH_AMERICAS",
	"EARTH_ASIA",
	"VOLCANO",
	"MILKY_WAY",
	"PARTLY_SUNNY",
	"OCTOCAT",
	"SQUIRREL",
	"BAMBOO",
	"GIFT_HEART",
	"DOLLS",
	"SCHOOL_SATCHEL",
	"MORTAR_BOARD",
	"FLAGS",
	"FIREWORKS",
	"SPARKLER",
	"WIND_CHIME",
	"RICE_SCENE",
	"JACK_O_LANTERN",
	"GHOST",
	"SANTA",
	"CHRISTMAS_TREE",
	"GIFT",
	"BELL",
	"NO_BELL",
	"TANABATA_TREE",
	"TADA",
	"CONFETTI_BALL",
	"BALLOON",
	"CRYSTAL_BALL",
	"CD",
	"DVD",
	"FLOPPY_DISK",
	"CAMERA",
	"VIDEO_CAMERA",
	"MOVIE_CAMERA",
	"COMPUTER",
	"TV",
	"IPHONE",
	"PHONE",
	"TELEPHONE",
	"TELEPHONE_RECEIVER",
	"PAGER",
	"FAX",
	"MINIDISC",
	"VHS",
	"SOUND",
	"SPEAKER",
	"MUTE",
	"LOUDSPEAKER",
	"MEGA",
	"HOURGLASS",
	"HOURGLASS_FLOWING_SAND",
	"ALARM_CLOCK",
	"WATCH",
	"RADIO",
	"SATELLITE",
	"LOOP",
	"MAG",
	"MAG_RIGHT",
	"UNLOCK",
	"LOCK",
	"LOCK_WITH_INK_PEN",
	"CLOSED_LOCK_WITH_KEY",
	"KEY",
	"BULB",
	"FLASHLIGHT",
	"HIGH_BRIGHTNESS",
	"LOW_BRIGHTNESS",
	"ELECTRIC_PLUG",
	"BATTERY",
	"CALLING",
	"EMAIL",
	"MAILBOX",
	"POSTBOX",
	"BATH",
	"BATHTUB",
	"SHOWER",
	"TOILET",
	"WRENCH",
	"NUT_AND_BOLT",
	"HAMMER",
	"SEAT",
	"MONEYBAG",
	"YEN",
	"DOLLAR",
	"POUND",
	"EURO",
	"CREDIT_CARD",
	"MONEY_WITH_WINGS",
	"E-MAIL",
	"INBOX_TRAY",
	"OUTBOX_TRAY",
	"ENVELOPE",
	"INCOMING_ENVELOPE",
	"POSTAL_HORN",
	"MAILBOX_CLOSED",
	"MAILBOX_WITH_MAIL",
	"MAILBOX_WITH_NO_MAIL",
	"DOOR",
	"SMOKING",
	"BOMB",
	"GUN",
	"HOCHO",
	"PILL",
	"SYRINGE",
	"PAGE_FACING_UP",
	"PAGE_WITH_CURL",
	"BOOKMARK_TABS",
	"BAR_CHART",
	"CHART_WITH_UPWARDS_TREND",
	"CHART_WITH_DOWNWARDS_TREND",
	"SCROLL",
	"CLIPBOARD",
	"CALENDAR",
	"DATE",
	"CARD_INDEX",
	"FILE_FOLDER",
	"OPEN_FILE_FOLDER",
	"SCISSORS",
	"PUSHPIN",
	"PAPERCLIP",
	"BLACK_NIB",
	"PENCIL2",
	"STRAIGHT_RULER",
	"TRIANGULAR_RULER",
	"CLOSED_BOOK",
	"GREEN_BOOK",
	"BLUE_BOOK",
	"ORANGE_BOOK",
	"NOTEBOOK",
	"NOTEBOOK_WITH_DECORATIVE_COVER",
	"LEDGER",
	"BOOKS",
	"BOOKMARK",
	"NAME_BADGE",
	"MICROSCOPE",
	"TELESCOPE",
	"NEWSPAPER",
	"FOOTBALL",
	"BASKETBALL",
	"SOCCER",
	"BASEBALL",
	"TENNIS",
	"8BALL",
	"RUGBY_FOOTBALL",
	"BOWLING",
	"GOLF",
	"MOUNTAIN_BICYCLIST",
	"BICYCLIST",
	"HORSE_RACING",
	"SNOWBOARDER",
	"SWIMMER",
	"SURFER",
	"SKI",
	"SPADES",
	"HEARTS",
	"CLUBS",
	"DIAMONDS",
	"GEM",
	"RING",
	"TROPHY",
	"MUSICAL_SCORE",
	"MUSICAL_KEYBOARD",
	"VIOLIN",
	"SPACE_INVADER",
	"VIDEO_GAME",
	"BLACK_JOKER",
	"FLOWER_PLAYING_CARDS",
	"GAME_DIE",
	"DART",
	"MAHJONG",
	"CLAPPER",
	"MEMO",
	"PENCIL",
	"BOOK",
	"ART",
	"MICROPHONE",
	"HEADPHONES",
	"TRUMPET",
	"SAXOPHONE",
	"GUITAR",
	"SHOE",
	"SANDAL",
	"HIGH_HEEL",
	"LIPSTICK",
	"BOOT",
	"SHIRT",
	"TSHIRT",
	"NECKTIE",
	"WOMANS_CLOTHES",
	"DRESS",
	"RUNNING_SHIRT_WITH_SASH",
	"JEANS",
	"KIMONO",
	"BIKINI",
	"RIBBON",
	"TOPHAT",
	"CROWN",
	"WOMANS_HAT",
	"MANS_SHOE",
	"CLOSED_UMBRELLA",
	"BRIEFCASE",
	"HANDBAG",
	"POUCH",
	"PURSE",
	"EYEGLASSES",
	"FISHING_POLE_AND_FISH",
	"COFFEE",
	"TEA",
	"SAKE",
	"BABY_BOTTLE",
	"BEER",
	"BEERS",
	"COCKTAIL",
	"TROPICAL_DRINK",
	"WINE_GLASS",
	"FORK_AND_KNIFE",
	"PIZZA",
	"HAMBURGER",
	"FRIES",
	"POULTRY_LEG",
	"MEAT_ON_BONE",
	"SPAGHETTI",
	"CURRY",
	"FRIED_SHRIMP",
	"BENTO",
	"SUSHI",
	"FISH_CAKE",
	"RICE_BALL",
	"RICE_CRACKER",
	"RICE",
	"RAMEN",
	"STEW",
	"ODEN",
	"DANGO",
	"EGG",
	"BREAD",
	"DOUGHNUT",
	"CUSTARD",
	"ICECREAM",
	"ICE_CREAM",
	"SHAVED_ICE",
	"BIRTHDAY",
	"CAKE",
	"COOKIE",
	"CHOCOLATE_BAR",
	"CANDY",
	"LOLLIPOP",
	"HONEY_POT",
	"APPLE",
	"GREEN_APPLE",
	"TANGERINE",
	"LEMON",
	"CHERRIES",
	"GRAPES",
	"WATERMELON",
	"STRAWBERRY",
	"PEACH",
	"MELON",
	"BANANA",
	"PEAR",
	"PINEAPPLE",
	"SWEET_POTATO",
	"EGGPLANT",
	"TOMATO",
	"CORN",
	"HOUSE",
	"HOUSE_WITH_GARDEN",
	"SCHOOL",
	"OFFICE",
	"POST_OFFICE",
	"HOSPITAL",
	"BANK",
	"CONVENIENCE_STORE",
	"LOVE_HOTEL",
	"HOTEL",
	"WEDDING",
	"CHURCH",
	"DEPARTMENT_STORE",
	"EUROPEAN_POST_OFFICE",
	"CITY_SUNRISE",
	"CITY_SUNSET",
	"JAPANESE_CASTLE",
	"EUROPEAN_CASTLE",
	"TENT",
	"FACTORY",
	"TOKYO_TOWER",
	"JAPAN",
	"MOUNT_FUJI",
	"SUNRISE_OVER_MOUNTAINS",
	"SUNRISE",
	"STARS",
	"STATUE_OF_LIBERTY",
	"BRIDGE_AT_NIGHT",
	"CAROUSEL_HORSE",
	"RAINBOW",
	"FERRIS_WHEEL",
	"FOUNTAIN",
	"ROLLER_COASTER",
	"SHIP",
	"SPEEDBOAT",
	"BOAT",
	"SAILBOAT",
	"ROWBOAT",
	"ANCHOR",
	"ROCKET",
	"AIRPLANE",
	"HELICOPTER",
	"STEAM_LOCOMOTIVE",
	"TRAM",
	"MOUNTAIN_RAILWAY",
	"BIKE",
	"AERIAL_TRAMWAY",
	"SUSPENSION_RAILWAY",
	"MOUNTAIN_CABLEWAY",
	"TRACTOR",
	"BLUE_CAR",
	"ONCOMING_AUTOMOBILE",
	"CAR",
	"RED_CAR",
	"TAXI",
	"ONCOMING_TAXI",
	"ARTICULATED_LORRY",
	"BUS",
	"ONCOMING_BUS",
	"ROTATING_LIGHT",
	"POLICE_CAR",
	"ONCOMING_POLICE_CAR",
	"FIRE_ENGINE",
	"AMBULANCE",
	"MINIBUS",
	"TRUCK",
	"TRAIN",
	"STATION",
	"TRAIN2",
	"BULLETTRAIN_FRONT",
	"BULLETTRAIN_SIDE",
	"LIGHT_RAIL",
	"MONORAIL",
	"RAILWAY_CAR",
	"TROLLEYBUS",
	"TICKET",
	"FUELPUMP",
	"VERTICAL_TRAFFIC_LIGHT",
	"TRAFFIC_LIGHT",
	"WARNING",
	"CONSTRUCTION",
	"BEGINNER",
	"ATM",
	"SLOT_MACHINE",
	"BUSSTOP",
	"BARBER",
	"HOTSPRINGS",
	"CHECKERED_FLAG",
	"CROSSED_FLAGS",
	"IZAKAYA_LANTERN",
	"MOYAI",
	"CIRCUS_TENT",
	"PERFORMING_ARTS",
	"ROUND_PUSHPIN",
	"TRIANGULAR_FLAG_ON_POST",
	"JP",
	"KR",
	"CN",
	"US",
	"FR",
	"ES",
	"IT",
	"RU",
	"GB",
	"UK",
	"DE",
	"ONE",
	"TWO",
	"THREE",
	"FOUR",
	"FIVE",
	"SIX",
	"SEVEN",
	"EIGHT",
	"NINE",
	"KEYCAP_TEN",
	"1234",
	"ZERO",
	"HASH",
	"SYMBOLS",
	"ARROW_BACKWARD",
	"ARROW_DOWN",
	"ARROW_FORWARD",
	"ARROW_LEFT",
	"CAPITAL_ABCD",
	"ABCD",
	"ABC",
	"ARROW_LOWER_LEFT",
	"ARROW_LOWER_RIGHT",
	"ARROW_RIGHT",
	"ARROW_UP",
	"ARROW_UPPER_LEFT",
	"ARROW_UPPER_RIGHT",
	"ARROW_DOUBLE_DOWN",
	"ARROW_DOUBLE_UP",
	"ARROW_DOWN_SMALL",
	"ARROW_HEADING_DOWN",
	"ARROW_HEADING_UP",
	"LEFTWARDS_ARROW_WITH_HOOK",
	"ARROW_RIGHT_HOOK",
	"LEFT_RIGHT_ARROW",
	"ARROW_UP_DOWN",
	"ARROW_UP_SMALL",
	"ARROWS_CLOCKWISE",
	"ARROWS_COUNTERCLOCKWISE",
	"REWIND",
	"FAST_FORWARD",
	"INFORMATION_SOURCE",
	"OK",
	"TWISTED_RIGHTWARDS_ARROWS",
	"REPEAT",
	"REPEAT_ONE",
	"NEW",
	"TOP",
	"UP",
	"COOL",
	"FREE",
	"NG",
	"CINEMA",
	"KOKO",
	"SIGNAL_STRENGTH",
	"U5272",
	"U5408",
	"U55B6",
	"U6307",
	"U6708",
	"U6709",
	"U6E80",
	"U7121",
	"U7533",
	"U7A7A",
	"U7981",
	"SA",
	"RESTROOM",
	"MENS",
	"WOMENS",
	"BABY_SYMBOL",
	"NO_SMOKING",
	"PARKING",
	"WHEELCHAIR",
	"METRO",
	"BAGGAGE_CLAIM",
	"ACCEPT",
	"WC",
	"POTABLE_WATER",
	"PUT_LITTER_IN_ITS_PLACE",
	"SECRET",
	"CONGRATULATIONS",
	"M",
	"PASSPORT_CONTROL",
	"LEFT_LUGGAGE",
	"CUSTOMS",
	"IDEOGRAPH_ADVANTAGE",
	"CL",
	"SOS",
	"ID",
	"NO_ENTRY_SIGN",
	"UNDERAGE",
	"NO_MOBILE_PHONES",
	"DO_NOT_LITTER",
	"NON-POTABLE_WATER",
	"NO_BICYCLES",
	"NO_PEDESTRIANS",
	"CHILDREN_CROSSING",
	"NO_ENTRY",
	"EIGHT_SPOKED_ASTERISK",
	"EIGHT_POINTED_BLACK_STAR",
	"HEART_DECORATION",
	"VS",
	"VIBRATION_MODE",
	"MOBILE_PHONE_OFF",
	"CHART",
	"CURRENCY_EXCHANGE",
	"ARIES",
	"TAURUS",
	"GEMINI",
	"CANCER",
	"LEO",
	"VIRGO",
	"LIBRA",
	"SCORPIUS",
	"SAGITTARIUS",
	"CAPRICORN",
	"AQUARIUS",
	"PISCES",
	"OPHIUCHUS",
	"SIX_POINTED_STAR",
	"NEGATIVE_SQUARED_CROSS_MARK",
	"A",
	"B",
	"AB",
	"O2",
	"DIAMOND_SHAPE_WITH_A_DOT_INSIDE",
	"RECYCLE",
	"END",
	"ON",
	"SOON",
	"CLOCK1",
	"CLOCK130",
	"CLOCK10",
	"CLOCK1030",
	"CLOCK11",
	"CLOCK1130",
	"CLOCK12",
	"CLOCK1230",
	"CLOCK2",
	"CLOCK230",
	"CLOCK3",
	"CLOCK330",
	"CLOCK4",
	"CLOCK430",
	"CLOCK5",
	"CLOCK530",
	"CLOCK6",
	"CLOCK630",
	"CLOCK7",
	"CLOCK730",
	"CLOCK8",
	"CLOCK830",
	"CLOCK9",
	"CLOCK930",
	"HEAVY_DOLLAR_SIGN",
	"COPYRIGHT",
	"REGISTERED",
	"TM",
	"X",
	"HEAVY_EXCLAMATION_MARK",
	"BANGBANG",
	"INTERROBANG",
	"O",
	"HEAVY_MULTIPLICATION_X",
	"HEAVY_PLUS_SIGN",
	"HEAVY_MINUS_SIGN",
	"HEAVY_DIVISION_SIGN",
	"WHITE_FLOWER",
	"100",
	"HEAVY_CHECK_MARK",
	"BALLOT_BOX_WITH_CHECK",
	"RADIO_BUTTON",
	"LINK",
	"CURLY_LOOP",
	"WAVY_DASH",
	"PART_ALTERNATION_MARK",
	"TRIDENT",
	"BLACK_SQUARE",
	"WHITE_SQUARE",
	"WHITE_CHECK_MARK",
	"BLACK_SQUARE_BUTTON",
	"WHITE_SQUARE_BUTTON",
	"BLACK_CIRCLE",
	"WHITE_CIRCLE",
	"RED_CIRCLE",
	"LARGE_BLUE_CIRCLE",
	"LARGE_BLUE_DIAMOND",
	"LARGE_ORANGE_DIAMOND",
	"SMALL_BLUE_DIAMOND",
	"SMALL_ORANGE_DIAMOND",
	"SMALL_RED_TRIANGLE",
	"SMALL_RED_TRIANGLE_DOWN",
	"SHIPIT",
}

return M
